export const StateWithCity = [
  {
    state: 'Andaman and Nicobar Islands (union territory)',
    cities: ['Port Blair'],
  },
  {
    state: 'Andhra Pradesh',
    cities: [
      'Adoni',
      'Amaravati',
      'Anantapur',
      'Chandragiri',
      'Chittoor',
      'Dowlaiswaram',
      'Eluru',
      'Guntur',
      'Kadapa',
      'Kakinada',
      'Kurnool',
      'Machilipatnam',
      'Nagarjunakoṇḍa',
      'Rajahmundry',
      'Srikakulam',
      'Tirupati',
      'Vijayawada',
      'Visakhapatnam',
      'Vizianagaram',
      'Yemmiganur',
    ],
  },
  {
    state: 'Arunachal Pradesh',
    cities: ['Itanagar'],
  },
  {
    state: 'Assam',
    cities: [
      'Dhuburi',
      'Dibrugarh',
      'Dispur',
      'Guwahati',
      'Jorhat',
      'Nagaon',
      'Sivasagar',
      'Silchar',
      'Tezpur',
      'Tinsukia',
    ],
  },
  {
    state: 'Bihar',
    cities: [
      'Ara',
      'Barauni',
      'Begusarai',
      'Bettiah',
      'Bhagalpur',
      'Bihar Sharif',
      'Bodh Gaya',
      'Buxar',
      'Chapra',
      'Darbhanga',
      'Dehri',
      'Dinapur Nizamat',
      'Gaya',
      'Hajipur',
      'Jamalpur',
      'Katihar',
      'Madhubani',
      'Motihari',
      'Munger',
      'Muzaffarpur',
      'Patna',
      'Purnia',
      'Pusa',
      'Saharsa',
      'Samastipur',
      'Sasaram',
      'Sitamarhi',
      'Siwan',
    ],
  },
  {
    state: 'Chandigarh (union territory)',
    cities: ['Chandigarh'],
  },
  {
    state: 'Chhattisgarh',
    cities: [
      'Ambikapur',
      'Bhilai',
      'Bilaspur',
      'Dhamtari',
      'Durg',
      'Jagdalpur',
      'Raipur',
      'Rajnandgaon',
    ],
  },
  {
    state: 'Dadra and Nagar Haveli and Daman and Diu (union territory)',
    cities: ['Daman', 'Diu', 'Silvassa'],
  },
  {
    state: 'Delhi (national capital territory)',
    cities: ['Delhi', 'New Delhi'],
  },
  {
    state: 'Goa',
    cities: ['Madgaon', 'Panaji'],
  },
  {
    state: 'Gujarat',
    cities: [
      'Ahmadabad',
      'Amreli',
      'Bharuch',
      'Bhavnagar',
      'Bhuj',
      'Dwarka',
      'Gandhinagar',
      'Godhra',
      'Jamnagar',
      'Junagadh',
      'Kandla',
      'Khambhat',
      'Kheda',
      'Mahesana',
      'Morbi',
      'Nadiad',
      'Navsari',
      'Okha',
      'Palanpur',
      'Patan',
      'Porbandar',
      'Rajkot',
      'Surat',
      'Surendranagar',
      'Valsad',
      'Veraval',
    ],
  },
  {
    state: 'Haryana',
    cities: [
      'Ambala',
      'Bhiwani',
      'Chandigarh',
      'Faridabad',
      'Firozpur Jhirka',
      'Gurugram',
      'Hansi',
      'Hisar',
      'Jind',
      'Kaithal',
      'Karnal',
      'Kurukshetra',
      'Panipat',
      'Pehowa',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sonipat',
    ],
  },
  {
    state: 'Himachal Pradesh',
    cities: [
      'Bilaspur',
      'Chamba',
      'Dalhousie',
      'Dharmshala',
      'Hamirpur',
      'Kangra',
      'Kullu',
      'Mandi',
      'Nahan',
      'Shimla',
      'Una',
    ],
  },
  {
    state: 'Jammu and Kashmir (union territory)',
    cities: [
      'Anantnag',
      'Baramula',
      'Doda',
      'Gulmarg',
      'Jammu',
      'Kathua',
      'Punch',
      'Rajouri',
      'Srinagar',
      'Udhampur',
    ],
  },
  {
    state: 'Jharkhand',
    cities: [
      'Bokaro',
      'Chaibasa',
      'Deoghar',
      'Dhanbad',
      'Dumka',
      'Giridih',
      'Hazaribag',
      'Jamshedpur',
      'Jharia',
      'Rajmahal',
      'Ranchi',
      'Saraikela',
    ],
  },
  {
    state: 'Karnataka',
    cities: [
      'Badami',
      'Ballari',
      'Bengaluru',
      'Belagavi',
      'Bhadravati',
      'Bidar',
      'Chikkamagaluru',
      'Chitradurga',
      'Davangere',
      'Halebid',
      'Hassan',
      'Hubballi-Dharwad',
      'Kalaburagi',
      'Kolar',
      'Madikeri',
      'Mandya',
      'Mangaluru',
      'Mysuru',
      'Raichur',
      'Shivamogga',
      'Shravanabelagola',
      'Shrirangapattana',
      'Tumakuru',
      'Vijayapura',
    ],
  },
  {
    state: 'Kerala',
    cities: [
      'Alappuzha',
      'Vatakara',
      'Idukki',
      'Kannur',
      'Kochi',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Mattancheri',
      'Palakkad',
      'Thalassery',
      'Thiruvananthapuram',
      'Thrissur',
    ],
  },
  {
    state: 'Ladakh (union territory)',
    cities: ['Kargil', 'Leh'],
  },
  {
    state: 'Madhya Pradesh',
    cities: [
      'Balaghat',
      'Barwani',
      'Betul',
      'Bharhut',
      'Bhind',
      'Bhojpur',
      'Bhopal',
      'Burhanpur',
      'Chhatarpur',
      'Chhindwara',
      'Damoh',
      'Datia',
      'Dewas',
      'Dhar',
      'Dr. Ambedkar Nagar (Mhow)',
      'Guna',
      'Gwalior',
      'Hoshangabad',
      'Indore',
      'Itarsi',
      'Jabalpur',
      'Jhabua',
      'Khajuraho',
      'Khandwa',
      'Khargone',
      'Maheshwar',
      'Mandla',
      'Mandsaur',
      'Morena',
      'Murwara',
      'Narsimhapur',
      'Narsinghgarh',
      'Narwar',
      'Neemuch',
      'Nowgong',
      'Orchha',
      'Panna',
      'Raisen',
      'Rajgarh',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Sarangpur',
      'Satna',
      'Sehore',
      'Seoni',
      'Shahdol',
      'Shajapur',
      'Sheopur',
      'Shivpuri',
      'Ujjain',
      'Vidisha',
    ],
  },
  {
    state: 'Maharashtra',
    cities: [
      'Ahmadnagar',
      'Akola',
      'Amravati',
      'Aurangabad',
      'Bhandara',
      'Bhusawal',
      'Bid',
      'Buldhana',
      'Chandrapur',
      'Daulatabad',
      'Dhule',
      'Jalgaon',
      'Kalyan',
      'Karli',
      'Kolhapur',
      'Mahabaleshwar',
      'Malegaon',
      'Matheran',
      'Mumbai',
      'Nagpur',
      'Nanded',
      'Nashik',
      'Osmanabad',
      'Pandharpur',
      'Parbhani',
      'Pune',
      'Ratnagiri',
      'Sangli',
      'Satara',
      'Sevagram',
      'Solapur',
      'Thane',
      'Ulhasnagar',
      'Vasai-Virar',
      'Wardha',
      'Yavatmal',
    ],
  },
  {
    state: 'Manipur',
    cities: ['Imphal'],
  },
  {
    state: 'Meghalaya',
    cities: ['Cherrapunji', 'Shillong'],
  },
  {
    state: 'Mizoram',
    cities: ['Aizawl', 'Lunglei'],
  },
  {
    state: 'Nagaland',
    cities: ['Kohima', 'Mon', 'Phek', 'Wokha', 'Zunheboto'],
  },
  {
    state: 'Odisha',
    cities: [
      'Balangir',
      'Baleshwar',
      'Baripada',
      'Bhubaneshwar',
      'Brahmapur',
      'Cuttack',
      'Dhenkanal',
      'Kendujhar',
      'Konark',
      'Koraput',
      'Paradip',
      'Phulabani',
      'Puri',
      'Sambalpur',
      'Udayagiri',
    ],
  },
  {
    state: 'Puducherry (union territory)',
    cities: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  },
  {
    state: 'Punjab',
    cities: [
      'Amritsar',
      'Batala',
      'Chandigarh',
      'Faridkot',
      'Firozpur',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Ludhiana',
      'Nabha',
      'Patiala',
      'Rupnagar',
      'Sangrur',
    ],
  },
  {
    state: 'Rajasthan',
    cities: [
      'Abu',
      'Ajmer',
      'Alwar',
      'Amer',
      'Barmer',
      'Beawar',
      'Bharatpur',
      'Bhilwara',
      'Bikaner',
      'Bundi',
      'Chittaurgarh',
      'Churu',
      'Dhaulpur',
      'Dungarpur',
      'Ganganagar',
      'Hanumangarh',
      'Jaipur',
      'Jaisalmer',
      'Jalor',
      'Jhalawar',
      'Jhunjhunu',
      'Jodhpur',
      'Kishangarh',
      'Kota',
      'Merta',
      'Nagaur',
      'Nathdwara',
      'Pali',
      'Phalodi',
      'Pushkar',
      'Sawai Madhopur',
      'Shahpura',
      'Sikar',
      'Sirohi',
      'Tonk',
      'Udaipur',
    ],
  },
  {
    state: 'Sikkim',
    cities: ['Gangtok', 'Gyalshing', 'Lachung', 'Mangan'],
  },
  {
    state: 'Tamil Nadu',
    cities: [
      'Arcot',
      'Chengalpattu',
      'Chennai',
      'Chidambaram',
      'Coimbatore',
      'Cuddalore',
      'Dharmapuri',
      'Dindigul',
      'Erode',
      'Kanchipuram',
      'Kanniyakumari',
      'Kodaikanal',
      'Kumbakonam',
      'Karur',
      'Madurai',
      'Mamallapuram',
      'Nagappattinam',
      'Nagercoil',
      'Namakkal',
      'Palayamkottai',
      'Perambalur',
      'Pudukkottai',
      'Rajapalayam',
      'Ramanathapuram',
      'Salem',
      'Sivaganga',
      'Thanjavur',
      'Tiruchirappalli',
      'Tirunelveli',
      'Tirupur',
      'Thoothukudi',
      'Udhagamandalam',
      'Vellore',
      'Villupuram',
    ],
  },
  {
    state: 'Telangana',
    cities: [
      'Adilabad',
      'Hyderabad',
      'Karimnagar',
      'Khammam',
      'Mahbubnagar',
      'Medak',
      'Nalgonda',
      'Nizamabad',
      'Rangareddy',
      'Warangal',
    ],
  },
  {
    state: 'Tripura',
    cities: ['Agartala'],
  },
  {
    state: 'Uttar Pradesh',
    cities: [
      'Agra',
      'Aligarh',
      'Amroha',
      'Ayodhya',
      'Azamgargh',
      'Bahraich',
      'Ballia',
      'Banda',
      'Bara Banki',
      'Bareilly',
      'Basti',
      'Bijnor',
      'Bithur',
      'Budaun',
      'Bulandshahr',
      'Deoria',
      'Etah',
      'Etawah',
      'Faizabad',
      'Farrukhabad',
      'Fatehpur',
      'Fatehpur Sikri',
      'Ghaziabad',
      'Ghazipur',
      'Gonda',
      'Gorakhpur',
      'Hamirpur',
      'Hapur',
      'Hardoi',
      'Hathras',
      'Jalaun',
      'Jaunpur',
      'Jhansi',
      'Kannauj',
      'Kanpur',
      'Lakhimpur',
      'Lalitpur',
      'Lucknow',
      'Mainpuri',
      'Mathura',
      'Meerut',
      'Mirzapur-Vindhyachal',
      'Moradabad',
      'Muzaffarnagar',
      'Noida',
      'Partapgarh',
      'Pilibhit',
      'Prayagraj',
      'Rae Bareli',
      'Rampur',
      'Saharanpur',
      'Sambhal',
      'Shahjahanpur',
      'Sitapur',
      'Sultanpur',
      'Tehri',
      'Varanasi',
    ],
  },
  {
    state: 'Uttarakhand',
    cities: [
      'Almora',
      'Dehradun',
      'Haridwar',
      'Mussoorie',
      'Nainital',
      'Pithoragarh',
      'Rishikesh',
      'Roorkee',
    ],
  },
  {
    state: 'West Bengal',
    cities: [
      'Alipore',
      'Alipur Duar',
      'Asansol',
      'Baharampur',
      'Bally',
      'Balurghat',
      'Bankurra',
      'Bardhaman',
      'Baranagar',
      'Barsat',
      'Barrackpore',
      'Basirhat',
      'Bhatpara',
      'Bishnupur',
      'Budge Budge',
      'Burdwan',
      'Cooch Bahar',
      'Chandernagore',
      'Darjeeling',
      'Diamond Harbour',
      'Dum Dum',
      'Durgapur',
      'Halisahar',
      'Howrah',
      'Hugli',
      'Ingraj Bazar',
      'Jalpaiguri',
      'Kalimpong',
      'Kamarhati',
      'Kanchrapara',
      'Kharagpur',
      'Kolkata',
      'Krishnanagar',
      'Malda',
      'Midnapore',
      'Murshidabad',
      'Nabadwip',
      'Nadia',
      'Palashi',
      'Panihati',
      'Purulia',
      'Raiganj',
      'Santipur',
      'Siliguri',
      'Siuri',
      'Sundarbans',
      'Shantiniketan',
      'Shrirampur',
      'Tamluk',
      'Titagarh',
    ],
  },
];
